=== Mastaleru/PlusPrivacy/clients/android-osdk/osdk/src/main/assets/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Operando Self-Compliance Document Schema",
  "description": "To describe and validate Operando certified applications self-compliance documents",
  "definitions": {
    "inputType": {
      "description": "A string describing the sensor type.",
      "type": "string",
      "enum": [
        "loc",
        "mic",
        "cam",
        "gyro",
        "acc",
        "prox",
        "touchID",
        "bar",
        "force",
        "pedo",
        "magneto",
        "contacts",
        "bat",
        "motion",
        "info"
      ]
    },
    "accessFrequency": {
      "description": "A string describing how often will the data be queried during an application's lifetime",
      "type": "string",
      "enum": [ "F1", "F2", "F3", "F4"]
    },
    "userControl": {
      "description": "A string describing whether the user has control over the process of gathering/querying data or not",
      "type": "string",
      "enum": ["C1", "C2", "C3"]
    }
  },
  "type": "object",
  "properties": {
    "appIconURL": {
      "type": "string",
      "description": "A valid url which points to the application's icon"
    },
    "bundleId": {
      "description": "A string which uniquely identifies the app",
      "type": "string"
    },
    "title": {
      "description": "The title of the app, as it will be displayed in Operando",
      "type": "string"
    },

    "sdkCheck": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["sdkName", "denyWithZeroValues"],
        "properties": {
          "sdkName": {"type": "string"},
          "denyWithZeroValues": {
            "type": "array",
            "items": { "$ref": "#/definitions/inputType"}
          }
        }
      }
    },

    "accessedHosts": {
      "description": "The list of hosts that the app will access or a reason for which these cannot be stated, such as the presence of a web browser in the app.",
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "hostList": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "hostList"
          ]
        },
        {
          "type": "object",
          "properties": {
            "reasonNonDisclosure": {
              "type": "string"
            }
          },
          "required": [
            "reasonNonDisclosure"
          ]
        }
      ]
    },
    "accessedInputs": {
      "description": "The list of items describing the accessed sensors and their security level",
      "type": "array",
      "items": {
        "description": "An object describing a sensor used by the application and it's security level",
        "type": "object",
        "properties": {
          "inputType": {"$ref": "#/definitions/inputType"},
          "privacyDescription": {
            "properties": {
              "usageLevel": {
                "description": "An integer describing the privacy level (which indicates how the data collected from this senser is being used. Corresponding to PL{i}",
                "type": "integer",
                "minimum": 1,
                "maximum": 6
              },
              "thirdParties": {
                "type": "array",
                "items": {
                  "description": "An object describing the third party to which data from this sensor is sent to.",
                  "type": "object",
                  "properties": {
                    "name": {
                      "description": "The third party identifier",
                      "type": "string"
                    },
                    "url": {
                      "description": "The url endpoint at which data from this sensor is sent",
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "url"
                  ]
                }
              }
            },
            "oneOf": [
              {
                "type": "object",
                "properties": {
                  "usageLevel": {
                    "enum": [
                      1,
                      2,
                      3,
                      4,
                      6
                    ]
                  }
                },
                "required": [
                  "usageLevel"
                ]
              },
              {
                "type": "object",
                "properties": {
                  "usageLevel": {
                    "enum": [
                      5
                    ]
                  }
                },
                "required": [
                  "usageLevel",
                  "thirdParties"
                ]
              }
            ]
          },
          "accessFrequency": {
            "$ref": "#/definitions/accessFrequency"
          },
          "userControl": {
            "$ref": "#/definitions/userControl"
          }
        },
        "required": [
          "inputType",
          "privacyDescription",
          "accessFrequency",
          "userControl"
        ]
      }
    }
  },
  "required": [
    "accessedInputs",
    "accessedHosts",
    "bundleId",
    "title"
  ]
}

=== Mastaleru/PlusPrivacy/clients/android-osdk/app/src/main/assets/AppSCD.json
{
  "title": "PlusPrivacy",
  "bundleId": "eu.romsoft.PlusPrivacy",
  "accessedHosts": {
    "reasonNonDisclosure": "PlusPrivacy integrates a web browser."
  },
  "accessedInputs": [
    {
      "inputType": "loc",
      "privacyDescription": {
        "usageLevel": 6,
        "thirdParties":[{
          "name": "http://httpbin.org",
          "url": "http://httpbin.org"
        }]
      },
      "accessFrequency": "F1",
      "userControl": "C1"
    },
    {
      "inputType": "contacts",
      "privacyDescription": {
        "usageLevel": 4
      },
      "accessFrequency": "F1",
      "userControl": "C2"
    },
    {
      "inputType": "cam",
      "privacyDescription": {
        "usageLevel": 5,
        "thirdParties":[{
          "name": "Facebook",
          "url": "wwww.facebook.com"
        }]
      },
      "accessFrequency": "F1",
      "userControl": "C2"
    }
  ]
}
